import React, { useState } from "react";
import Chart from "react-google-charts";

const COMP_SCALE = {
  FREELANCER: "Freelancer",
  STARTUP_1_TO_10: "Start Up (1 - 10) (Early)",
  STARTUP_10_TO_100: "Start Up (10 - 100) (Medium)",
  STARTUP_100_PLUS: "Start Up (100 +) (Large)",
  SERVICE_5_TO_50: "Service (5 - 50)",
  SERVICE_50_TO_100: "Service (50 - 100)",
  SERVICE_100_PLUS: "Service (100 +)",
  ENTERPRISE_MED: "Enterprise Medium",
  ENTERPRISE_LARGE: "Enterprise Large",
  FORTUNE_500s: "Fortune 500s",
};

const DEV_CYCLE = {
  MARKET_RESEARCH: "Market Research",
  BUSINESS_REQ: "Business Requirements",
  DESIGN: "Design",
  PROTOTYPE: "Prototype",
  SYSTEMS_DESIGN: "Systems Design",
  SPRINT_PLANNING: "Sprint Planning",
  FRONTEND_COMPONENT_LIB: "Frontend Component Library",
  FRONTEND_UI_MOCK_UP: "Frontend UI Mock-Ups",
  FRONTEND_UI_DEVELOPMENT: "Frontend UI Development",
  BUSINESS_LOGIC: "Business Logic",
  BACKEND_INTEGRATION: "Backend Integration",
  UNIT_TESTING: "Unit Testing",
  E2E_TESTING: "E2E Testing",
  DEPLOYMENT: "Deployment",
  MAINTAINANCE: "Maintainance",
};

const FEATURES = {
  UPLOAD_DESIGN_SYSTEM: "Upload Design System",
  ANNOTATE_COMPONENT: "Annotate Components",
  AUTO_LAYOUT: "Automatic Layout",
  REUSABLE_COMPONENT: "Re-Usable Component",
  COMPONENT_LIB_VERSIONING: "Component Library Versioning",
  GENERATE_COMP_CODE: "Generate Component Code",
  GENERATE_PAGE_CODE: "Generate Page Code",
  FACILITATE_ROUTING: "Facilitate Routing",
  GENERIC_HOOKS: "Generic Hooks",
  BASIC_AUTH: "Basic Auth",
  API_HANDLERS: "API Handlers",
  MICROINTERACTIONS: "Micro-Interactions",
  MICRO_STATE_MGMT: "Micro state Management",
  CSS_TRANSITIONS: "CSS Transitions",
  TYPESCRIPT: "Typescript Support",
  SYNC_UI_DESIGN_CHANGES: "Sync UI Design Changes (Round Tripping)",
  TEAM_USER_MGMT: "Team and User Management",
  GIT_VERSION_CONTROL: "Github Version Control",
  STORYBOOK: "StoryBook",
  GLOBAL_STATE_MGMT: "Global State Management",
};

const FW_AND_COMP_LIB = {
  MUI: "Material UI",
  TAILWIND: "Tailwind CSS",
  CHAKRA: "Chakra UI",
  ANT_DESIGN: "Ant Design",
  STYLED: "Styled Components",
  BLUEPRINT: "Buleprint UI",
  NEXTJS: "Next Js",
};

const initData = [
  ["From", "To", "Weight"],
  // [COMP_SCALE.FREELANCER, DEV_CYCLE.MARKET_RESEARCH, 1],
  // [COMP_SCALE.FREELANCER, DEV_CYCLE.BUSINESS_REQ, 1],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.DESIGN, 2],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 3],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 8],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.BUSINESS_LOGIC, 4],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.BACKEND_INTEGRATION, 1],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.E2E_TESTING, 1],
  [COMP_SCALE.FREELANCER, DEV_CYCLE.DEPLOYMENT, 1],
  // FREELANCER END

  // [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.MARKET_RESEARCH, 8],
  // [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.BUSINESS_REQ, 6],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.DESIGN, 3],
  // [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.SYSTEMS_DESIGN, 6],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.PROTOTYPE, 1],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 2],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 6],
  // [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.BUSINESS_LOGIC, 7],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.BACKEND_INTEGRATION, 3],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.E2E_TESTING, 1],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.UNIT_TESTING, 1],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.DEPLOYMENT, 1],
  [COMP_SCALE.STARTUP_1_TO_10, DEV_CYCLE.MAINTAINANCE, 2],
  // STARTUP_1_TO_10 END

  // [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.MARKET_RESEARCH, 4],
  // [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.BUSINESS_REQ, 8],
  // [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.DESIGN, 3],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.PROTOTYPE, 1],
  // [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.SYSTEMS_DESIGN, 2],
  // [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.SPRINT_PLANNING, 7],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 3],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 2],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 6],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.BUSINESS_LOGIC, 2],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.BACKEND_INTEGRATION, 3],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.UNIT_TESTING, 2],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.E2E_TESTING, 0],
  // [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.DEPLOYMENT, 9],
  [COMP_SCALE.STARTUP_10_TO_100, DEV_CYCLE.MAINTAINANCE, 1],

  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.MARKET_RESEARCH, 3],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.BUSINESS_REQ, 9],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.DESIGN, 0],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.PROTOTYPE, 4],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.SYSTEMS_DESIGN, 7],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.SPRINT_PLANNING, 2],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 4],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 2],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 4],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.BUSINESS_LOGIC, 3],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.BACKEND_INTEGRATION, 2],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.UNIT_TESTING, 2],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.E2E_TESTING, 3],
  // [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.DEPLOYMENT, 3],
  [COMP_SCALE.STARTUP_100_PLUS, DEV_CYCLE.MAINTAINANCE, 3],



  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.MARKET_RESEARCH, 0],
  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.BUSINESS_REQ, 1],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.DESIGN, 1],
  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.PROTOTYPE, 0],
  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.SYSTEMS_DESIGN, 6],
  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.SPRINT_PLANNING, 3],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 1],
  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 3],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 6],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.BUSINESS_LOGIC, 4],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.BACKEND_INTEGRATION, 2],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.UNIT_TESTING, 2],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.E2E_TESTING, 2],
  // [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.DEPLOYMENT, 4],
  [COMP_SCALE.SERVICE_5_TO_50, DEV_CYCLE.MAINTAINANCE, 2],
  // SERVICE_5_TO_50 END

  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.MARKET_RESEARCH, 0],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.BUSINESS_REQ, 2],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.DESIGN, 4],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.PROTOTYPE, 1],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.SYSTEMS_DESIGN, 7],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.SPRINT_PLANNING, 6],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 3],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 2],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 6],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.BUSINESS_LOGIC, 2],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.BACKEND_INTEGRATION, 2],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.UNIT_TESTING, 2],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.E2E_TESTING, 7],
  // [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.DEPLOYMENT, 3],
  [COMP_SCALE.SERVICE_50_TO_100, DEV_CYCLE.MAINTAINANCE, 4],



  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.MARKET_RESEARCH, 6],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.BUSINESS_REQ, 2],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.DESIGN, 4],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.PROTOTYPE, 2],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.SYSTEMS_DESIGN, 2],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.SPRINT_PLANNING, 3],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 4],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 4],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 6],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.BUSINESS_LOGIC, 3],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.BACKEND_INTEGRATION, 1],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.UNIT_TESTING, 2],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.E2E_TESTING, 8],
  // [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.DEPLOYMENT, 2],
  [COMP_SCALE.SERVICE_100_PLUS, DEV_CYCLE.MAINTAINANCE, 5],
  // SERVICE_100_PLUS END





  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.MARKET_RESEARCH, 0],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.BUSINESS_REQ, 5],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.DESIGN, 3],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.PROTOTYPE, 1],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.SYSTEMS_DESIGN, 5],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.SPRINT_PLANNING, 6],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 2],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 0],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 7],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.BUSINESS_LOGIC, 2],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.BACKEND_INTEGRATION, 2],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.UNIT_TESTING, 2],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.E2E_TESTING, 2],
  // [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.DEPLOYMENT, 7],
  [COMP_SCALE.ENTERPRISE_MED, DEV_CYCLE.MAINTAINANCE, 4],
  // ENTERPRISE_MED END



  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.MARKET_RESEARCH, 0],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.BUSINESS_REQ, 3],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.DESIGN, 2],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.PROTOTYPE, 3],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.SYSTEMS_DESIGN, 2],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.SPRINT_PLANNING, 6],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.FRONTEND_COMPONENT_LIB, 3],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.FRONTEND_UI_MOCK_UP, 5],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, 6],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.BUSINESS_LOGIC, 2],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.BACKEND_INTEGRATION, 2],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.UNIT_TESTING, 2],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.E2E_TESTING, 3],
  // [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.DEPLOYMENT, 7],
  [COMP_SCALE.ENTERPRISE_LARGE, DEV_CYCLE.MAINTAINANCE, 4],
  // ENTERPRISE_LARGE END

  
  [DEV_CYCLE.DESIGN, FEATURES.UPLOAD_DESIGN_SYSTEM, 3],
  [DEV_CYCLE.DESIGN, FEATURES.ANNOTATE_COMPONENT, 2],
  [DEV_CYCLE.DESIGN, FEATURES.AUTO_LAYOUT, 2],
  [DEV_CYCLE.DESIGN, FEATURES.REUSABLE_COMPONENT, 2],
  [DEV_CYCLE.DESIGN, FEATURES.COMPONENT_LIB_VERSIONING, 1],
  [DEV_CYCLE.DESIGN, FEATURES.GENERATE_COMP_CODE, 1],
  [DEV_CYCLE.DESIGN, FEATURES.GENERATE_PAGE_CODE, 1],
  [DEV_CYCLE.DESIGN, FEATURES.FACILITATE_ROUTING, 1],
  // [DEV_CYCLE.DESIGN, FEATURES.GENERIC_HOOKS, 5],
  // [DEV_CYCLE.DESIGN, FEATURES.BASIC_AUTH, 4],
  // [DEV_CYCLE.DESIGN, FEATURES.API_HANDLERS, 2],
  [DEV_CYCLE.DESIGN, FEATURES.MICROINTERACTIONS, 3],
  // [DEV_CYCLE.DESIGN, FEATURES.MICRO_STATE_MGMT, 5],
  [DEV_CYCLE.DESIGN, FEATURES.CSS_TRANSITIONS, 2],
  // [DEV_CYCLE.DESIGN, FEATURES.TYPESCRIPT, 4],
  [DEV_CYCLE.DESIGN, FEATURES.SYNC_UI_DESIGN_CHANGES, 1],
  [DEV_CYCLE.DESIGN, FEATURES.TEAM_USER_MGMT, 1],
  // [DEV_CYCLE.DESIGN, FEATURES.GIT_VERSION_CONTROL, 6],
  [DEV_CYCLE.DESIGN, FEATURES.STORYBOOK, 2],
  // [DEV_CYCLE.DESIGN, FEATURES.GLOBAL_STATE_MGMT, 1],


  [DEV_CYCLE.PROTOTYPE, FEATURES.CSS_TRANSITIONS, 7 ],
  [DEV_CYCLE.PROTOTYPE, FEATURES.MICRO_STATE_MGMT, 7 ],
  [DEV_CYCLE.PROTOTYPE, FEATURES.MICROINTERACTIONS, 7 ],

  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.UPLOAD_DESIGN_SYSTEM, 2],
  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.ANNOTATE_COMPONENT, 1],
  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.AUTO_LAYOUT, 9],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.REUSABLE_COMPONENT, 3],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.COMPONENT_LIB_VERSIONING, 2],
  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.GENERATE_COMP_CODE, 3],
  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.GENERATE_PAGE_CODE, 4],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.FACILITATE_ROUTING, 1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.GENERIC_HOOKS,1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.BASIC_AUTH, 1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.API_HANDLERS, 1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.MICROINTERACTIONS, 2],
  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.MICRO_STATE_MGMT, 1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.CSS_TRANSITIONS, 1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.TYPESCRIPT, 1],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.SYNC_UI_DESIGN_CHANGES, 1],
  // [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.TEAM_USER_MGMT, 6],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.GIT_VERSION_CONTROL, 2],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.STORYBOOK, 4],
  [DEV_CYCLE.FRONTEND_COMPONENT_LIB, FEATURES.GLOBAL_STATE_MGMT, 2],



  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.UPLOAD_DESIGN_SYSTEM, 5],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.ANNOTATE_COMPONENT, 4],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.AUTO_LAYOUT, 3],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.REUSABLE_COMPONENT, 2],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.COMPONENT_LIB_VERSIONING, 8],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.GENERATE_COMP_CODE, 1],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.GENERATE_PAGE_CODE, 1],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.FACILITATE_ROUTING, 1],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.GENERIC_HOOKS, 8],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.BASIC_AUTH, 8],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.API_HANDLERS, 5],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.MICROINTERACTIONS, 1],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.MICRO_STATE_MGMT, 1],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.CSS_TRANSITIONS, 2],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.TYPESCRIPT, 1],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.SYNC_UI_DESIGN_CHANGES, 2],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.TEAM_USER_MGMT, 1],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.GIT_VERSION_CONTROL, 5],
  // [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.STORYBOOK, 2],
  [DEV_CYCLE.FRONTEND_UI_MOCK_UP, FEATURES.GLOBAL_STATE_MGMT, 2],



  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.UPLOAD_DESIGN_SYSTEM, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.ANNOTATE_COMPONENT, 2],
  // [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.AUTO_LAYOUT, 4],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.REUSABLE_COMPONENT, 2],
  // [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.COMPONENT_LIB_VERSIONING, 9],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.GENERATE_COMP_CODE, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.GENERATE_PAGE_CODE, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.FACILITATE_ROUTING, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.GENERIC_HOOKS, 1],
  // [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.BASIC_AUTH, 8],
  // [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.API_HANDLERS, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.MICROINTERACTIONS, 2],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.MICRO_STATE_MGMT, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.CSS_TRANSITIONS, 2],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.TYPESCRIPT, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.SYNC_UI_DESIGN_CHANGES, 2],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.TEAM_USER_MGMT, 2],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.GIT_VERSION_CONTROL, 2],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.STORYBOOK, 1],
  [DEV_CYCLE.FRONTEND_UI_DEVELOPMENT, FEATURES.GLOBAL_STATE_MGMT, 1],



  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.UPLOAD_DESIGN_SYSTEM, 2],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.ANNOTATE_COMPONENT, 0],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.AUTO_LAYOUT, 4],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.REUSABLE_COMPONENT, 9],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.COMPONENT_LIB_VERSIONING, 2],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.GENERATE_COMP_CODE, 9],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.GENERATE_PAGE_CODE, 0],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.FACILITATE_ROUTING, 2],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.GENERIC_HOOKS, 2],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.BASIC_AUTH, 1],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.API_HANDLERS, 2],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.MICROINTERACTIONS, 3],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.MICRO_STATE_MGMT, 1],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.CSS_TRANSITIONS, 9],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.TYPESCRIPT, 1],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.SYNC_UI_DESIGN_CHANGES, 0],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.TEAM_USER_MGMT, 2],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.GIT_VERSION_CONTROL, 3],
  // [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.STORYBOOK, 1],
  [DEV_CYCLE.BUSINESS_LOGIC, FEATURES.GLOBAL_STATE_MGMT, 3],

  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.UPLOAD_DESIGN_SYSTEM, 1],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.ANNOTATE_COMPONENT, 4],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.AUTO_LAYOUT, 7],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.REUSABLE_COMPONENT, 3],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.COMPONENT_LIB_VERSIONING, 3],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.GENERATE_COMP_CODE, 0],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.GENERATE_PAGE_CODE, 1],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.FACILITATE_ROUTING, 1],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.GENERIC_HOOKS, 2],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.BASIC_AUTH, 2],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.API_HANDLERS, 3],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.MICROINTERACTIONS, 2],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.MICRO_STATE_MGMT, 0],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.CSS_TRANSITIONS, 0],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.TYPESCRIPT, 1],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.SYNC_UI_DESIGN_CHANGES, 1],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.TEAM_USER_MGMT, 3],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.GIT_VERSION_CONTROL, 2],
  // [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.STORYBOOK, 1],
  [DEV_CYCLE.BACKEND_INTEGRATION, FEATURES.GLOBAL_STATE_MGMT, 4],




  // [DEV_CYCLE.UNIT_TESTING, FEATURES.UPLOAD_DESIGN_SYSTEM, 7],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.ANNOTATE_COMPONENT, 3],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.AUTO_LAYOUT, 3],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.REUSABLE_COMPONENT, 3],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.COMPONENT_LIB_VERSIONING, 5],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.GENERATE_COMP_CODE, 0],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.GENERATE_PAGE_CODE, 9],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.FACILITATE_ROUTING, 2],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.GENERIC_HOOKS, 0],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.BASIC_AUTH, 2],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.API_HANDLERS, 3],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.MICROINTERACTIONS, 4],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.MICRO_STATE_MGMT, 2],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.CSS_TRANSITIONS, 5],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.TYPESCRIPT, 5],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.SYNC_UI_DESIGN_CHANGES, 1],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.TEAM_USER_MGMT, 3],
  [DEV_CYCLE.UNIT_TESTING, FEATURES.GIT_VERSION_CONTROL, 3],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.STORYBOOK, 6],
  // [DEV_CYCLE.UNIT_TESTING, FEATURES.GLOBAL_STATE_MGMT, 1],



  // [DEV_CYCLE.E2E_TESTING, FEATURES.UPLOAD_DESIGN_SYSTEM, 8],
 // [DEV_CYCLE.E2E_TESTING, FEATURES.UPLOAD_DESIGN_SYSTEM, 7],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.ANNOTATE_COMPONENT, 3],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.AUTO_LAYOUT, 3],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.REUSABLE_COMPONENT, 3],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.COMPONENT_LIB_VERSIONING, 5],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.GENERATE_COMP_CODE, 0],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.GENERATE_PAGE_CODE, 9],
  [DEV_CYCLE.E2E_TESTING, FEATURES.FACILITATE_ROUTING, 2],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.GENERIC_HOOKS, 0],
  [DEV_CYCLE.E2E_TESTING, FEATURES.BASIC_AUTH, 2],
  [DEV_CYCLE.E2E_TESTING, FEATURES.API_HANDLERS, 3],
  [DEV_CYCLE.E2E_TESTING, FEATURES.MICROINTERACTIONS, 4],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.MICRO_STATE_MGMT, 2],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.CSS_TRANSITIONS, 5],
  [DEV_CYCLE.E2E_TESTING, FEATURES.TYPESCRIPT, 5],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.SYNC_UI_DESIGN_CHANGES, 1],
  [DEV_CYCLE.E2E_TESTING, FEATURES.TEAM_USER_MGMT, 3],
  [DEV_CYCLE.E2E_TESTING, FEATURES.GIT_VERSION_CONTROL, 3],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.STORYBOOK, 6],
  // [DEV_CYCLE.E2E_TESTING, FEATURES.GLOBAL_STATE_MGMT, 1],


  // [DEV_CYCLE.MAINTAINANCE, FEATURES.UPLOAD_DESIGN_SYSTEM, 0],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.ANNOTATE_COMPONENT, 6],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.AUTO_LAYOUT, 0],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.REUSABLE_COMPONENT, 8],
  [DEV_CYCLE.MAINTAINANCE, FEATURES.COMPONENT_LIB_VERSIONING, 6],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.GENERATE_COMP_CODE, 8],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.GENERATE_PAGE_CODE, 3],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.FACILITATE_ROUTING, 2],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.GENERIC_HOOKS, 0],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.BASIC_AUTH, 7],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.API_HANDLERS, 9],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.MICROINTERACTIONS, 5],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.MICRO_STATE_MGMT, 2],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.CSS_TRANSITIONS, 9],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.TYPESCRIPT, 0],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.SYNC_UI_DESIGN_CHANGES, 3],
  [DEV_CYCLE.MAINTAINANCE, FEATURES.TEAM_USER_MGMT, 5],
  [DEV_CYCLE.MAINTAINANCE, FEATURES.GIT_VERSION_CONTROL, 5],
  [DEV_CYCLE.MAINTAINANCE, FEATURES.STORYBOOK, 5],
  // [DEV_CYCLE.MAINTAINANCE, FEATURES.GLOBAL_STATE_MGMT, 2],

  // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.MUI, 4],
  // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.TAILWIND, 5],
  // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.CHAKRA, 4],
  // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.ANT_DESIGN, 3],
  // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.STYLED, 2],
  // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.BLUEPRINT, 2],
  // // [FEATURES.UPLOAD_DESIGN_SYSTEM, FW_AND_COMP_LIB.NEXTJS, 1],


  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.MUI, 4],
  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.TAILWIND, 4],
  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.CHAKRA, 4],
  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.ANT_DESIGN, 3],
  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.STYLED, 2],
  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.BLUEPRINT, 1],
  // [FEATURES.ANNOTATE_COMPONENT, FW_AND_COMP_LIB.NEXTJS, 2],


  // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.MUI, 5],
  // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.TAILWIND, 2],
  // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.CHAKRA, 5],
  // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.ANT_DESIGN, 4],
  // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.STYLED, 2],
  // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.BLUEPRINT, 2],
  // // [FEATURES.AUTO_LAYOUT, FW_AND_COMP_LIB.NEXTJS, 1],



  // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.MUI, 5],
  // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.TAILWIND, 2],
  // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.CHAKRA, 4],
  // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.ANT_DESIGN, 4],
  // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.STYLED, 1],
  // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.BLUEPRINT, 4],
  // // [FEATURES.REUSABLE_COMPONENT, FW_AND_COMP_LIB.NEXTJS, 0],


  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.MUI, 4],
  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.TAILWIND, 3],
  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.CHAKRA, 9],
  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.ANT_DESIGN, 6],
  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.STYLED, 2],
  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.BLUEPRINT, 6],
  // [FEATURES.COMPONENT_LIB_VERSIONING, FW_AND_COMP_LIB.NEXTJS, 3],


  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.MUI, 7],
  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.TAILWIND, 4],
  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.CHAKRA, 6],
  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.ANT_DESIGN, 6],
  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.STYLED, 6],
  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.BLUEPRINT, 6],
  // [FEATURES.GENERATE_COMP_CODE, FW_AND_COMP_LIB.NEXTJS, 7],


  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.MUI, 5],
  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.TAILWIND, 0],
  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.CHAKRA, 7],
  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.ANT_DESIGN, 6],
  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.STYLED, 3],
  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.BLUEPRINT, 6],
  // [FEATURES.GENERATE_PAGE_CODE, FW_AND_COMP_LIB.NEXTJS, 3],



  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.MUI, 0],
  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.TAILWIND, 4],
  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.CHAKRA, 4],
  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.ANT_DESIGN, 3],
  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.STYLED, 8],
  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.BLUEPRINT, 9],
  // [FEATURES.FACILITATE_ROUTING, FW_AND_COMP_LIB.NEXTJS, 4],


  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.MUI, 7],
  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.TAILWIND, 1],
  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.CHAKRA, 9],
  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.ANT_DESIGN, 6],
  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.STYLED, 7],
  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.BLUEPRINT, 1],
  // [FEATURES.GENERIC_HOOKS, FW_AND_COMP_LIB.NEXTJS, 8],



  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.MUI, 0],
  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.TAILWIND, 8],
  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.CHAKRA, 8],
  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.ANT_DESIGN, 7],
  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.STYLED, 3],
  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.BLUEPRINT, 4],
  // [FEATURES.BASIC_AUTH, FW_AND_COMP_LIB.NEXTJS, 6],



  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.MUI, 6],
  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.TAILWIND, 1],
  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.CHAKRA, 5],
  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.ANT_DESIGN, 9],
  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.STYLED, 9],
  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.BLUEPRINT, 5],
  // [FEATURES.API_HANDLERS, FW_AND_COMP_LIB.NEXTJS, 9],



  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.MUI, 6],
  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.TAILWIND, 1],
  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.CHAKRA, 1],
  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.ANT_DESIGN, 7],
  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.STYLED, 6],
  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.BLUEPRINT, 9],
  // [FEATURES.MICROINTERACTIONS, FW_AND_COMP_LIB.NEXTJS, 2],



  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.MUI, 7],
  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.TAILWIND, 8],
  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.CHAKRA, 8],
  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.ANT_DESIGN, 2],
  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.STYLED, 8],
  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.BLUEPRINT, 9],
  // [FEATURES.MICRO_STATE_MGMT, FW_AND_COMP_LIB.NEXTJS, 6],


  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.MUI, 7],
  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.TAILWIND, 3],
  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.CHAKRA, 1],
  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.ANT_DESIGN, 0],
  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.STYLED, 0],
  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.BLUEPRINT, 5],
  // [FEATURES.CSS_TRANSITIONS, FW_AND_COMP_LIB.NEXTJS, 9],

  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.MUI, 8],
  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.TAILWIND, 8],
  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.CHAKRA, 4],
  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.ANT_DESIGN, 4],
  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.STYLED, 6],
  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.BLUEPRINT, 2],
  // [FEATURES.TYPESCRIPT, FW_AND_COMP_LIB.NEXTJS, 9],



  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.MUI, 5],
  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.TAILWIND, 2],
  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.CHAKRA, 8],
  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.ANT_DESIGN, 1],
  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.STYLED, 9],
  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.BLUEPRINT, 3],
  // [FEATURES.SYNC_UI_DESIGN_CHANGES, FW_AND_COMP_LIB.NEXTJS, 0],



  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.MUI, 1],
  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.TAILWIND, 6],
  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.CHAKRA, 3],
  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.ANT_DESIGN, 8],
  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.STYLED, 2],
  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.BLUEPRINT, 7],
  // [FEATURES.TEAM_USER_MGMT, FW_AND_COMP_LIB.NEXTJS, 5],


  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.MUI, 2],
  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.TAILWIND, 1],
  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.CHAKRA, 7],
  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.ANT_DESIGN, 1],
  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.STYLED, 3],
  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.BLUEPRINT, 3],
  // [FEATURES.GIT_VERSION_CONTROL, FW_AND_COMP_LIB.NEXTJS, 5],



  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.MUI, 3],
  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.TAILWIND, 8],
  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.CHAKRA, 7],
  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.ANT_DESIGN, 1],
  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.STYLED, 1],
  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.BLUEPRINT, 1],
  // [FEATURES.STORYBOOK, FW_AND_COMP_LIB.NEXTJS, 8],


  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.MUI, 3],
  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.TAILWIND, 1],
  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.CHAKRA, 9],
  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.ANT_DESIGN, 3],
  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.STYLED, 5],
  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.BLUEPRINT, 5],
  // [FEATURES.GLOBAL_STATE_MGMT, FW_AND_COMP_LIB.NEXTJS, 0],
]

var colors = [];
 
let i = 0;
var letters = "0123456789ABCDEF";

const generateRandColor = () => {
  var color = "#";
  for (let k = 0; k < 6; k++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
};
while (i < initData.length) {
  const kkC = generateRandColor();
  if (!colors.includes(kkC)) {
    colors.push(kkC);
    i++;
  }
}

var options = {
  height: 800,
  width: 1500,
  sankey: {
    node: {
      interactivity: true, // Allows you to select nodes.
      labelPadding: 6, // Horizontal distance between the label and the node.
      colors: colors,
      nodePadding: 10, // Vertical distance between nodes.
      color: {
        fill: "#fff", // Color of the link.
        fillOpacity: 0.18, // Transparency of the link.
        strokeWidth: 10, // Thickness of the link border (default 0).
      },
    },
    link: {
      colorMode: "gradient",
      colors: colors,
    },
  },
};
function App() {

  
const [showEditor,setShowEditor ] = useState(false)


const [ data, setData ] = useState(initData);

  return (
    <>
      <h1 style={{ fontFamily: "ubuntu" }}> User Segmentation</h1>

      <Chart
        chartType="Sankey"
        width="100%"
        height="500px"
        data={data}
        options={options}
        legendToggle
      />
    </>
  );
}

export default App;
